### ISSUE TITLE
AjaxLogger sets contentType: 'application/json' incorrectly

### ISSUE THREAD

**Issue by robbie-c** [mixu/minilog#28]
Currently each line is individually a valid JSON string, but the whole body itself is not. Currently it looks like:

    ["myApp","info",some text"]
    ["myApp","info","some more text"]
    ["myApp","info","even more text"]

when really it should look like this:

    {"logs: [
      ["myApp","info",some text"]
      ["myApp","info","some more text"]
      ["myApp","info","even more text"]
    ]}

If we're not prepared to do this, we should absolutely not set the contentType to be 'application/json'. This screws up the node json body-parser, which will try to JSON.parse the whole body if the contentType matches.

**Comment by saikat** [comment]
I believe this is the line that needs to get changed, but haven't tested: https://github.com/mixu/minilog/blob/master/lib/web/jquery_simple.js#L37
